---
title: "ShinyApp"
author: "R. Spellenberg"
date: "2023-02-15"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = FALSE)
library(tidyverse)
library(here)
```

```{r}
counties <- read_csv(here("data", "counties_irrigation.csv"))
```

```{r}
### some data viz to get us started (waiting on data with crop type from Anna)

```


```{r Ashley Cooper}
### Ashley codes here

### Graphics for Landing Page

county_et_plot <- ggplot(data = et_counties_clean_dropna,
                      aes(x = name, y = et_mm_year)) +
  geom_histogram(aes(fill = name), color = "darkslategray", binwidth = 1, show.legend = FALSE) +
  scale_color_viridis_b() +
  labs(title = "", x = "County", y = "Average Annual Evapotranspiration (mm)") +
  theme_bw()


  # map_fill <- reactive({
  #   final_sf %>%
  #     filter(var == input$pick_variable_map)
  # })
  # 
  # # var_color <- reactive({
  # #   color_list %>% 
  # #     pluck(input$pick_variable_map)
  # # })
  # 
  # 
  # output$ca_map <- renderPlot({
  #   
  # 
  #   ggplot() + 
  #     geom_sf(data = map_fill(), aes(fill = values, geometry = geometry),
  #             color = 'black', size = 0.1) +
  #     theme_void()
  #     # scale_fill_gradient2(colors = 'red') +
  # })

### Coding my actual code
county_plot_fill <- reactive({
    final_sf %>%
      filter(name == input$select_county, var == input$pick_variable)

county_plot <- ggplot(data = county_plot_fill,
       aes(x = name, y = values)) +
  geom_jitter(aes(color = name), width = 0.2, size = 0.5, show.legend = FALSE) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  scale_color_manual(values = var_color) +
  labs(title = "C", x = "Species", y = "Height (cm)") +
  theme_bw()

```


```{r Sydney Mayes}
### Sydney codes here

# Anna's original code
scalar = 1.2 # turns mm/month to cm/year
ggplot(filter(et_crops, type == "ag_ET"), aes(x = reorder(cropnames, ET))) + 
  geom_linerange(data = filter(et_crops, type == "ag_ET"), aes(ymax = min*scalar, ymin = max*scalar), color = "seagreen") + 
  geom_col(data = filter(et_crops, type != "ET"), aes(y = ET*scalar, fill = type), alpha = .6) +
  scale_fill_manual(values=c(ag_ET="seagreen", ET_pred="goldenrod4"), breaks=c("ag_ET","ET_pred"), labels = c("Agricultural ET", "Simulated natural ET")) + 
  geom_col(data = filter(et_crops, type == "ET"), aes(y = ET*scalar, color = type), alpha = 0) +
  scale_color_manual(values=c("navyblue"), labels = c("Observed ET")) + 
  geom_linerange(data = filter(et_crops, type == "ET"), aes(ymax = min*scalar, ymin = max*scalar), color = "navyblue") + 
  geom_linerange(data = filter(et_crops, type == "ag_ET"), aes(ymax = min*scalar, ymin = max*scalar), color = "seagreen") + 
  ylab("cm/year") + 
  theme_classic() + 
  labs(fill='') + 
  theme(axis.text.x = element_text(angle = 30, hjust=1), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        legend.position = "top", 
        legend.direction="horizontal", 
        legend.title=element_blank())


# Taking out observed ET

scalar = 1.2 # turns mm/month to cm/year

ggplot(filter(et_crops, type == "ag_ET"), aes(x = reorder(cropnames, ET))) + 
  geom_linerange(data = filter(et_crops, type == "ag_ET"), aes(ymax = min*scalar, ymin = max*scalar), color = "seagreen") + 
  geom_col(data = filter(et_crops, type != "ET"), aes(y = ET*scalar, fill = type), alpha = .6) +
  scale_fill_manual(values=c(ag_ET="seagreen", ET_pred="goldenrod4"), breaks=c("ag_ET","ET_pred"), labels = c("Agricultural ET", "Simulated natural ET")) +
  geom_linerange(data = filter(et_crops, type == "ag_ET"), aes(ymax = min*scalar, ymin = max*scalar), color = "seagreen") + 
  ylab("cm/year") + 
  theme_classic() + 
  labs(fill='') + 
  theme(axis.text.x = element_text(angle = 30, hjust=1), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        legend.position = "top", 
        legend.direction="horizontal", 
        legend.title=element_blank())

# Just AG ET
scalar = 1.2
ggplot(filter(et_crops, type == "ag_ET"), aes(x = reorder(cropnames, ET))) + 
  geom_col(data = filter(et_crops, type == "ag_ET"), aes(y = ET*scalar, fill = type), alpha = .6) +
  scale_fill_manual(values=c(ag_ET="seagreen", ET_pred="goldenrod4"), breaks=c("ag_ET","ET_pred"), labels = c("Agricultural ET", "Simulated natural ET")) +
  ylab("cm/year") + 
  theme_classic() + 
  labs(fill='') + 
  theme(axis.text.x = element_text(angle = 30, hjust=1), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        legend.position = "top", 
        legend.direction="horizontal", 
        legend.title=element_blank())

# Just Predicted ET 
scalar = 1.2
ggplot(filter(et_crops, type == "ag_ET"), aes(x = reorder(cropnames, ET))) + 
  geom_col(data = filter(et_crops, type == "ET_pred"), aes(y = ET*scalar, fill = type), alpha = .6) +
  scale_fill_manual(values=c(ag_ET="seagreen", ET_pred="goldenrod4"), breaks=c("ag_ET","ET_pred"), labels = c("Agricultural ET", "Simulated natural ET")) + 
  ylab("cm/year") + 
  theme_classic() + 
  labs(fill='') + 
  theme(axis.text.x = element_text(angle = 30, hjust=1), 
        axis.title.x=element_blank(), 
        axis.ticks.x=element_blank(), 
        legend.position = "top", 
        legend.direction="horizontal", 
        legend.title=element_blank())

```


```{r Rachel Spellenberg}
### Rachel codes here



```